name: virtual_tennis_mentor
description: "Application helps storing informations about our oponents, results and tactics"

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: 8.1.6
  equatable: 2.0.5
  dartz: 0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mocktail: ^1.0.4
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
